# Generated by Django 5.1.15 on 2026-07-03 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arendatori',
            fields=[
                ('id_arendator', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('adresa', models.CharField(max_length=255)),
                ('cnp', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_serie', models.CharField(max_length=255)),
                ('ci_nr', models.CharField(max_length=255)),
                ('ci_el', models.CharField(max_length=255)),
                ('ci_data', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'arendatori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfigAn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('an', models.CharField(max_length=4, unique=True)),
                ('pret_kg_grau', models.DecimalField(blank=True, decimal_places=2, help_text='Preț kg grâu la primărie pentru anul respectiv', max_digits=10, null=True)),
                ('pret_kg_porumb', models.DecimalField(blank=True, decimal_places=2, help_text='Preț kg porumb la primărie pentru anul respectiv', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config_an',
                'ordering': ['-an'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
                ('updated_at', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contracte',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('nr_contract', models.CharField(max_length=255)),
                ('data_contract', models.DateField()),
                ('perioada_contract', models.CharField(max_length=255)),
                ('nivel_arenda', models.CharField(max_length=255)),
                ('observatii', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arendator', models.ForeignKey(db_column='id_arendator', on_delete=django.db.models.deletion.CASCADE, related_name='contracte', to='api.arendatori')),
            ],
            options={
                'db_table': 'contracte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arenda',
            fields=[
                ('id_arenda', models.AutoField(primary_key=True, serialize=False)),
                ('an_arenda', models.CharField(max_length=4)),
                ('nivel_lei', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('neachitat', 'Neachitat'), ('achitat_partial', 'Achitat Parțial'), ('achitat_integral', 'Achitat Integral')], default='neachitat', max_length=20)),
                ('contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, related_name='arende', to='api.contracte')),
            ],
            options={
                'db_table': 'arenda',
                'managed': True,
                'unique_together': {('contract', 'an_arenda')},
            },
        ),
        migrations.CreateModel(
            name='Aditionale',
            fields=[
                ('id_aditional', models.AutoField(primary_key=True, serialize=False)),
                ('nr_aditional', models.CharField(max_length=255)),
                ('data_aditional', models.DateField()),
                ('perioada_aditional', models.CharField(max_length=255)),
                ('nivel_arenda', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, related_name='aditionale', to='api.contracte')),
            ],
            options={
                'db_table': 'aditionale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlatiArenda',
            fields=[
                ('id_plata', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True)),
                ('data_generarii', models.DateTimeField(auto_now_add=True)),
                ('data_plata', models.DateTimeField(blank=True, null=True)),
                ('tip_plata', models.CharField(choices=[('lei', 'Lei'), ('grau', 'Grâu'), ('porumb', 'Porumb')], max_length=10)),
                ('cantitate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valoare_lei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metoda_plata', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer Bancar'), ('ridicare', 'Ridicare')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('generata', 'Generată'), ('platita', 'Plătită'), ('anulata', 'Anulată')], default='generata', max_length=20)),
                ('observatii', models.TextField(blank=True)),
                ('scans', models.IntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('oblio_invoice_id', models.CharField(blank=True, help_text='Oblio invoice ID for federation', max_length=255, null=True)),
                ('oblio_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Oblio'), ('FAILED', 'Submission Failed'), ('SYNCED', 'Synced to SPV')], default='DRAFT', help_text='Invoice status in Oblio', max_length=20)),
                ('oblio_error', models.TextField(blank=True, help_text='Last error from Oblio API', null=True)),
                ('oblio_submitted_at', models.DateTimeField(blank=True, help_text='When this was last submitted to Oblio', null=True)),
                ('invoice_idempotency_key', models.CharField(blank=True, help_text='UUID for API idempotency (prevents duplicates)', max_length=255, null=True)),
                ('invoice_audit_trail', models.JSONField(default=dict, help_text="Audit log: [{'timestamp': '...', 'action': '...', 'status': '...'}]")),
                ('arenda', models.ForeignKey(db_column='id_arenda', on_delete=django.db.models.deletion.CASCADE, related_name='plati', to='api.arenda')),
            ],
            options={
                'db_table': 'plati_arenda',
                'ordering': ['-data_generarii'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Terenuri',
            fields=[
                ('id_teren', models.AutoField(primary_key=True, serialize=False)),
                ('act_proprietate', models.CharField(max_length=255)),
                ('nr_act_proprietate', models.CharField(max_length=255)),
                ('data_act_proprietate', models.DateField(blank=True, null=True)),
                ('suprafata', models.CharField(max_length=255)),
                ('tarla', models.CharField(max_length=255)),
                ('parcela', models.CharField(max_length=255)),
                ('vecin_nord', models.CharField(blank=True, max_length=255, null=True)),
                ('vecin_est', models.CharField(blank=True, max_length=255, null=True)),
                ('vecin_sud', models.CharField(blank=True, max_length=255, null=True)),
                ('vecin_vest', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie_teren', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arendator', models.ForeignKey(db_column='id_arendator', on_delete=django.db.models.deletion.CASCADE, related_name='terenuri', to='api.arendatori')),
                ('contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, related_name='terenuri', to='api.contracte')),
                ('zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, related_name='terenuri', to='api.zone')),
            ],
            options={
                'db_table': 'terenuri',
                'managed': True,
            },
        ),
    ]
